[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "adblite"
version = "0.2.0"
description = "A lightweight ADB, scrcpy and custom command desktop tool"
requires-python = ">=3.9"
dependencies = ["PySide6>=6.7,<6.9"]

[project.scripts]
adblite = "adblite.main:main"

[tool.setuptools.packages.find]
where = ["src"]
